### PR TITLE
A failing test for sequence + either

### PR DESCRIPTION
**Pull request by TehShrike**
I found a case where `either` should be wrapped in a non-capturing group, but is not.

In this test case, `sequence('thingy', either(/[a]/, /b/))` produces `thingy[a]|b` when it should produce `/thingy(?:[a]|b)/`.

### CODE REVIEW

**Comment by TehShrike** [comment]
Without the square brackets around `a`, the non-capturing group is correctly added.

**Comment by TehShrike** [comment]
`isSequential` and `isOneGroup` scare me.  I would much rather have simpler code that inserts unnecessary non-capturing groups.

**Comment by pygy** [comment]
Thanks for the PR, and good catch.

`isSequential` and `isOneGroup` are simple parsers, You've understood their purpose correctly.

The way character sets is handled is suboptimal and obviously buggy...

Looking into it...

**Comment by pygy** [comment]
Thanks for the test case, this was due to a typo (`match === ']` rather than `match[0] === ']'`).

**Pull request merged**
