### PR TITLE
Adding "optional" function

### PR DESCRIPTION
**Pull request by TehShrike**
Allows you to make chunks of the regex optional.

### CODE REVIEW

**Comment by pygy** [comment]
Thanks for the PR, I'm not sure we need this, because it can be derived from the current API.

It's probably not obvious, but you can get it as

```JS
var optional = greedy.bind(null, '?')
```

I usually call it `maybe`...

**Comment by TehShrike** [comment]
Yeah, I hadn't looked at `greedy` at all - it seems kind of weird that a function named `greedy` would allow the suffix `?`, which doesn't do a greedy-thing at all - how would you feel about an internal function named something like `addSuffix` that would be used by both `greedy` (which would check `validSuffix`) and a new slim `maybe` function?

I love the library, by the way - definitely the right way to compose regular expressions.

**Comment by pygy** [comment]
It is a greedy optional. The non-greedy operator is `??` (the proper term is "reluctant", I came up with `frugal` because I didn't know any better at the time).

Compare:

```JS
"a".match(/(a?)(a*)/)  // [ 'a', 'a', '', index: 0, input: 'a' ]
"a".match(/(a??)(a*)/) // [ 'a', '', 'a', index: 0, input: 'a' ]
```

**Comment by pygy** [comment]
`maybe = greedy.bind(null, '?')` was actually given as an example in the `greedy()` section...

I'm going to reject the PR, because the approach is IMO too restrictive and specific. I want however to thank you for the kind words, and for pointing out a shortcoming in the API.

I've updated `greedy` and `frugal` to make them curried.

Now `greedy('*', 'x').source === greedy('*')('x').source`, so you can define `optional = greedy('?')`.

**Comment by pygy** [comment]
It is out as `v0.2`. I hadn't read your last comment in full, but ended up taking a similar approach to `addSuffix` to implement the curried version (see `operator`).

**Comment by TehShrike** [comment]
I'm familiar with how greedy operators work, I had just been operating with a wrong idea about what the greedy function returned.

I hadn't bothered reading the details on the `greedy` function because I didn't need greedy matching. :-x

The implementation of `greedy` is fine, I only worry that the name is confusing.  I want to add a suffix, not make a quantifier greedy.

**Comment by pygy** [comment]
What if we got rid of `greedy()` and `frugal()` (which is poorly named anyway) and used `suffix() for everything`?

**Comment by TehShrike** [comment]
I would be way down for that.  👍

I'd be very comfortable using `suffix` to give myself `greedy`/`frugal`/`maybe` as I need them.

**Comment by pygy** [comment]
API Updated (plus bug fixes and streamlining of the innards... see `v0.4`)

**Comment by TehShrike** [comment]
On a quick skim, it looks good to me, but when I upgraded from 0.1.8 to 0.4.0 in [verse-reference-regex](https://github.com/tehshrike/verse-reference-regex), it started spitting out a different regular expression that produced different capture grouping output.  I'll try to take a deeper look tomorrow and get a proper reproduction.

**Comment by pygy** [comment]
It's not surprising it produced a different expression, the previous version was inserting at the same time too many and not enough non-capturing groups...

`sequence(/a/, /b|c/)` was resulting in `/ab|c/` rather than `/a(?:b|c)/`, for example. `greedy('*', 'a')` would give `(?:a)*`, now `suffix('*', 'a')` returns `/a*/` (but `suffix('*', 'ab')` still returns `/(?:ab)*/`.

That being said, there are most likely bugs in the new code as well (I'm now parsing regexps to determine if the have a top-level choice operator and if they need parens before applying a suffix), the test suite is anything but thorough...

**Comment by pygy** [comment]
@TehShrike did you ever manage to repro the capture difference between v0.1.8 and v0.4?

**Comment by TehShrike** [comment]
Thanks for the poke.  I finally got a good reproduction, I'll open a pull request with a failing test.

**Comment by TehShrike** [comment]
See #3

**Pull request closed without merging**
